Q1 What are data structures and why are they  impotant ?

  ->Data structures are fundamental to computer science, defining how data is organized, stored, and processed in a computer system..


 Q2 Explain the differnce between mutable and immutable data types with example ?

   ->Mutable data types are those that can be changed after they are created, while immutable data types cannot be changed once created. Examples of mutable data types include lists, dictionaries, and sets..


 Q3 What are the main differences between lists and tuples in Python?


   -> Lists are mutable while tuples are immutable..


 Q4 Describe how dictionaries store data ?

   -> dictionaries stored data in key-value format or in unordered format..


 Q5 Why might you use a set instead of a list in Python?

   -> Because set stores data in inordered format or set also performs mathmatical operations while sets are unique in itself ..


 Q6 What is string in python,and how it is different from lists?

   -> A string is a sequence of characters between single or double quotes. A list is a sequence of items, where each item could be anything (an integer, a float, a string, etc)


 Q7 How do tuples ensure data integrity in Python?

-> Tuples in Python ensure data integrity through their immutability. Once a tuple is created, its elements cannot be modified, added, or removed.  



 Q8 What is a hash table, and how does it relate to dictionaries in Python?

  -> A hash table is a data structure that stores key-value pairs, using a hash function to compute an index for each key ..


 Q9 Can lists contain different data types in Python ?

   -> YES.


 Q10 Explain why strings are immutable in puthon ?

  ->  strings can be used as keys in dictionaries. If strings were mutable, their hash values could change..


 Q11 What advantages do dictionaries offer over lists for certain tasks ?

  ->   It gives more flexibility when storing data. The primary advantage would be retrieving stored values as it is much simpler to search through a dictionary.


 Q12  Describe a scenario where using a tuple would be preferable over a list ?

  -> Use a tuple if you need an immutable collection where the elements won't change after creation.


 Q13  How do sets handle duplicate values in Python ?

  -> Sets in Python are designed to store only unique elements. When an attempt is made to add a duplicate value to a set, Python automatically discards the duplicate, ensuring that the set retains only distinct values.


 Q14 How does the “in” keyword work differently for lists and dictionaries ?

  -> The in operator in Python checks if a specified value exists within a sequence, such as a list, tuple, or string ..


 Q15 Can you modify the elements of a tuple? Explain why or why not ?

  -> No, you cannot directly modify the elements of a tuple in Python after it has been created. Tuples are immutable ..


 Q16  What is a nested dictionary, and give an example of its use case ?

  -> A nested dictionary in Python is a dictionary whose values are themselves dictionaries ..


 Q17 Describe the time complexity of accessing elements in a dictionary ?

  -> Accessing an element in a dictionary using its key typically has a time complexity of O(1) on average ..


 Q18 In what situations are lists preferred over dictionaries ?

 -> For ordered collections and sequence operations, such as maintaining a stack or queue and also they are faster for index based access..

 Q19  Why are dictionaries considered unordered, and how does that affect data retrieval ?

  -> The items do not have a defined order, you cannot refer to an item by using an index and  providing a fast and efficient way to access data using key-value pairs.


 Q20 Explain the difference between a list and a dictionary in terms of data retrieval ?

 -> , a dictionary offers significantly faster access to elements compared to a list, especially when dealing with large datasets.

PRACTICAL QUESTIONS

 Q1 Write a code to create a string with your name and print it ?

In [ ]:
 Name = "vivek gupta"
 print(Name)
 print(type(Name))

vivek gupta
<class 'str'>

Q2  Write a code to find the length of the string "Hello World" ?

In [ ]:
str1 = "Hello World"
print(len(str1))

11

Q3 Write a code to slice the first 3 characters from the string "Python Programming ?

In [ ]:
str1 = "python programming"
print(str1[0:3])

pyt

Q4  Write a code to convert the string "hello" to uppercase ?

In [1]:
string = "hello"
uppercase_string = string.upper()
print(uppercase_string)

HELLO

Q5 Write a code to replace the word "apple" with "orange" in the string "I like apple"?

In [5]:
str1="i like apple"
str2=str1.replace("apple","orange")
print(str2)

i like orange

Q6  Write a code to create a list with numbers 1 to 5 and print it ?

In [1]:
numbers = [1,2,3,4,5]
print(numbers)
print(type(numbers))

[1, 2, 3, 4, 5]
<class 'list'>

Q7 Write a code to append the number 10 to the list [1, 2, 3, 4]?

In [3]:
numbers = [1,2,3,4,5]
numbers.append(10)
print(numbers)

[1, 2, 3, 4, 5, 10]

Q8 Write a code to remove the number 3 from the list [1, 2, 3, 4, 5] ?

In [4]:
numbers =[1,2,3,4,5]
numbers.remove(3)
print(numbers)

[1, 2, 4, 5]

Q9 Write a code to access the second element in the list ['a', 'b', 'c', 'd']?

In [5]:
elements=['a','b','c','d']
print(elements[1])

b

Q10 Write a code to reverse the list [10, 20, 30, 40, 50]?

In [6]:
LIST=[10,20,30,40,50]
LIST.reverse()
print(LIST)

[50, 40, 30, 20, 10]

Q11  Write a code to create a tuple with the elements 100, 200, 300 and print it ?

In [7]:
tup=(100,200,300)
print(tup)
print(type(tup))

(100, 200, 300)
<class 'tuple'>

Q12 Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')?

In [13]:
TUPLE = ('red', 'green', 'blue', 'yellow')
print(TUPLE[2])

blue

Q13 . Write a code to find the minimum number in the tuple (10, 20, 5, 15)?

In [14]:
TUPLE = (10, 20, 5, 15)
print(min(TUPLE))

5

Q14  Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit')?

In [15]:
ELEMENTS=('dog', 'cat', 'rabbit')
print(ELEMENTS.index('cat'))

1

Q15 . Write a code to create a tuple containing three different fruits and check if "kiwi" is in it?

In [16]:
TUPLE=('apple','banana','kiwi')
print('kiwi' in TUPLE)

True

Q16  Write a code to create a set with the elements 'a', 'b', 'c' and print it ?

In [17]:
set1={'a','b','c'}
print(set1)
print(type(set1))

{'b', 'a', 'c'}
<class 'set'>

Q17  Write a code to clear all elements from the set {1, 2, 3, 4, 5}?

In [18]:
ELEMENTS={1,2,3,4,5}
ELEMENTS.clear()
print(ELEMENTS)

set()

Q18 Write a code to remove the element 4 from the set {1, 2, 3, 4} ?

In [19]:
SET1={1,2,3,4}
SET1.remove(4)
print(SET1)

{1, 2, 3}

Q19  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}?

In [22]:
SET1={1,2,3}
SET2={3,4,5}
print(SET1.union(SET2))

{1, 2, 3, 4, 5}

Q2O  Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}?

In [23]:
SET1={1,2,3}
SET2={2,3,4}
print(SET1.intersection(SET2))

{2, 3}

Q21  Write a code to create a dictionary with the keys "name", "age", and "city", and print it?

In [25]:
DICT={ "name":"vivek","age":20,"city":"lucknow"}
print(DICT)
print(type(DICT))

{'name': 'vivek', 'age': 20, 'city': 'lucknow'}
<class 'dict'>

Q22 Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}?

In [27]:
DICT={'name': 'John', 'age': 25}
DICT['country']="USA"
print(DICT)

{'name': 'John', 'age': 25, 'country': 'USA'}

Q23 Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30} ?

In [30]:
DICT={'name': 'Alice', 'age': 30}
print(DICT['name'])

Alice

Q24 Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}?

In [31]:
DICT={'name': 'Bob', 'age': 22, 'city': 'New York'}
DICT.pop('age')
print(DICT)

{'name': 'Bob', 'city': 'New York'}

Q25 Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}?

In [32]:
DICT={'name': 'Alice', 'city': 'Paris'}
print('city' in DICT)

True

Q26  Write a code to create a list, a tuple, and a dictionary, and print them all?

In [33]:
LIST=[1,2,3,4,5]
print(LIST)
print(type(LIST))
TUPLE=(1,2,3,4,5)
print(TUPLE)
print(type(TUPLE))
DICT={1:'a',2:'b',3:'c'}
print(DICT)
print(type(DICT))1

[1, 2, 3, 4, 5]
<class 'list'>
(1, 2, 3, 4, 5)
<class 'tuple'>
{1: 'a', 2: 'b', 3: 'c'}
<class 'dict'>

Q27  Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
result.(replaced)?

In [37]:
LIST=[1,2,3,4,5]
LIST.sort()
print(LIST)

[1, 2, 3, 4, 5]

Q28 Write a code to create a list with strings and print the element at the third index ?

In [38]:
LIST=['a','b','c','d','e']
print(LIST[3])

d

Q29 Write a code to combine two dictionaries into one and print the result?

In [39]:
DICT1={'a':1,'b':2}
DICT2={'c':3,'d':4}
DICT1.update(DICT2)
print(DICT1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

Q30  Write a code to convert a list of strings into a set?

In [40]:
list1=['a','b','c','d']
set1=set(list1)
print(set1)

{'b', 'd', 'a', 'c'}